apiVersion: integration/v1
kind: Integration
name: opsgenie
channel: alpha
version: v20200522
summary: Relay integration for Opsgenie
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-opsgenie

description: |
  This integration provides access to Opsgenie, a real-time operations and
  incident response platform from Atlassian.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
- rto
- incident response
