apiVersion: integration/v1
kind: Trigger
name: opsgenie-trigger-alert-created
version: 1
summary: Opsgenie Alert created 
description: |
  This trigger fires when an OpsGenie alert is created for the first time.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker
